# This playbook installs additional nmap libraries and scripts.
#
# Copyright (c) 2013 Fabian Affolter <fabian@affolter-engineering.ch>
#
# All rights reserved.
# This file is licensed under GPLv2, for more details check COPYING.
# 
# Usage: ansible-playbook nmap-scripts.yml -f 10

---
#- hosts: fsl_hosts
- hosts: 127.0.0.1
  connection: local
  user: root
  vars:
    # Development librarieres from nmap which are not part of the official release
    - libs: [tls.lua]
    # Additional scripts
    - nse: []
    # Additional external scripts (incl. the full URL)
    - nse-external: []

  tasks:
  - name: download nmap libraries from nmap
    get_url: url=https://svn.nmap.org/nmap/nselib/{{ item }}
             dest=/usr/share/nmap/nselib/{{ item }}
             mode=0644
    with_items: libs

  - name: copy the nmap scripts
    copy: src={{ item }}
          dest=/usr/share/nmap/scripts/
          mode=0644
    with_items: nse

  - name: download nmap scripts
    get_url: url={{ item }}
             dest=/usr/share/nmap/scripts/
             mode=0644
    with_items: nse-external
 
  - name: update nmap database
    command: /usr/bin/nmap --script-updatedb
